### PR TITLE
Take pictures using LERF embeddings; visualize grounding results in 3D mesh

### PR DESCRIPTION
**Pull request by XuweiyiChen**
- allow picture taking with 0.3 second/rgb rendering with 512 by 512

### CODE REVIEW

**Comment by XuweiyiChen** [comment]
- glb is enabled but might have minor issue

**Comment by XuweiyiChen** [comment]
dockerfiles && save lerf and nerfstudio changes

**Comment by jedyang97** [comment]
[This line in lerf-lite](https://github.com/sled-group/lerf_lite/blob/59992f7b5490e086b215d9fa1c4c79ca5f0a3324/pyproject.toml#L12) should be changed to `"nerfstudio"` (without the `>=0.3.0) cuz otherwise in the dockerfile when we install lerf-lite our custom installation of nerfstudio will be overwritten by the official installation of nerfstudio 0.3.0.

**Comment by jedyang97** [comment]
[This line](https://github.com/sled-group/lerf_lite/blob/98315522fce45490cbfdd226a1baef436f00413b/lerf/lerf.py#L15) in lerf-lite is causing error:
```
Exception has occurred: ConstructorError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
while constructing a Python object
cannot find module 'lerf.lerf_pipeline' (cannot import name 'ColormapOptions' from 'nerfstudio.utils.colormaps' (/home/user/nerfstudio_export/nerfstudio/utils/colormaps.py))
  in "<unicode string>", line 85, column 11:
    pipeline: !!python/object:lerf.lerf_pipeli ... 
              ^
  File "/home/user/.local/lib/python3.10/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
  File "/home/user/lerf_lite/lerf/lerf_pipeline.py", line 19, in <module>
    from lerf.lerf import LERFModel, LERFModelConfig
  File "/home/user/lerf_lite/lerf/lerf.py", line 15, in <module>
    from nerfstudio.utils.colormaps import ColormapOptions, apply_colormap
ImportError: cannot import name 'ColormapOptions' from 'nerfstudio.utils.colormaps' 
```

`ColormapOptions`, `apply_colormap` are actually never used in `lerf.py`. Just remove those import lines.

**Pull request closed without merging**
